#!/usr/bin/env node
// Regenerates TypeScript types (packages/core/src/generated) and Pydantic
// models (services/solver/generated) from schemas/*.schema.json.
//
// Adding a schema here is the only wiring a new schema needs for codegen;
// `pnpm schemas:check` (used in CI) fails if the committed output is stale.
import { compile } from 'json-schema-to-typescript';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));

const SCHEMAS = [
  {
    schemaPath: 'schemas/ingredient.schema.json',
    tsOut: 'packages/core/src/generated/ingredient.ts',
    tsName: 'Ingredient',
    tsSchemaOut: 'packages/core/src/generated/ingredient.schema.ts',
    tsSchemaConst: 'ingredientJsonSchema',
    pyOut: 'services/solver/generated/ingredient.py',
  },
  {
    schemaPath: 'schemas/recipe.schema.json',
    tsOut: 'packages/core/src/generated/recipe.ts',
    tsName: 'Recipe',
    tsSchemaOut: 'packages/core/src/generated/recipe.schema.ts',
    tsSchemaConst: 'recipeJsonSchema',
    pyOut: 'services/solver/generated/recipe.py',
  },
];

// Small reference data files (schemas/*.json, not *.schema.json): wrapped as
// typed TS constants so packages/core can read them without doing file I/O
// at call time. schemas/*.json stays the single source of truth (data-model
// principle 1); this keeps the TS copy from drifting out of sync with it.
const CONFIG_FILES = [
  { jsonPath: 'schemas/locales.json', constName: 'localesConfig' },
  { jsonPath: 'schemas/capabilities.json', constName: 'capabilitiesConfig' },
  { jsonPath: 'schemas/diet-rules.json', constName: 'dietRulesConfig' },
];
const CONFIG_OUT = 'packages/core/src/generated/config.ts';

const TS_HEADER =
  '// AUTO-GENERATED by scripts/generate-schemas.mjs from schemas/*.schema.json.\n// Do not edit by hand — see docs/data-model.md.\n\n';
const PY_HEADER =
  '# AUTO-GENERATED by scripts/generate-schemas.mjs from schemas/*.schema.json.\n# Do not edit by hand — see docs/data-model.md.\n';

async function generateTs({ schemaPath, tsOut, tsName, tsSchemaOut, tsSchemaConst }) {
  const schema = JSON.parse(readFileSync(resolve(rootDir, schemaPath), 'utf-8'));
  const ts = await compile(schema, tsName, {
    bannerComment: '',
    additionalProperties: false,
  });
  const outPath = resolve(rootDir, tsOut);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, TS_HEADER + ts);
  console.log(`wrote ${tsOut}`);

  const schemaOutPath = resolve(rootDir, tsSchemaOut);
  const schemaTs = `${TS_HEADER}export const ${tsSchemaConst} = ${JSON.stringify(schema, null, 2)} as const;\n`;
  writeFileSync(schemaOutPath, schemaTs);
  console.log(`wrote ${tsSchemaOut}`);
}

function generateConfigTs() {
  const parts = CONFIG_FILES.map(({ jsonPath, constName }) => {
    const data = JSON.parse(readFileSync(resolve(rootDir, jsonPath), 'utf-8'));
    return `export const ${constName} = ${JSON.stringify(data, null, 2)} as const;\n`;
  });
  const outPath = resolve(rootDir, CONFIG_OUT);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, TS_HEADER + parts.join('\n'));
  console.log(`wrote ${CONFIG_OUT}`);
}

function generatePy({ schemaPath, pyOut }) {
  const outPath = resolve(rootDir, pyOut);
  mkdirSync(dirname(outPath), { recursive: true });
  execFileSync(
    'uv',
    [
      'run',
      'datamodel-codegen',
      '--input',
      resolve(rootDir, schemaPath),
      '--input-file-type',
      'jsonschema',
      '--output',
      outPath,
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--target-python-version',
      '3.12',
      '--use-standard-collections',
      '--disable-timestamp',
      '--use-schema-description',
    ],
    { cwd: resolve(rootDir, 'services/solver'), stdio: 'inherit' },
  );
  const body = readFileSync(outPath, 'utf-8');
  writeFileSync(outPath, PY_HEADER + body);
  console.log(`wrote ${pyOut}`);
}

for (const entry of SCHEMAS) {
  await generateTs(entry);
  generatePy(entry);
}
generateConfigTs();

console.log('Schema codegen complete.');
