#!/usr/bin/env node
// Regenerates TypeScript types (packages/core/src/generated) and Pydantic
// models (services/solver/generated) from schemas/*.schema.json.
//
// Adding a schema here is the only wiring a new schema needs for codegen;
// `pnpm schemas:check` (used in CI) fails if the committed output is stale.
import { compile } from 'json-schema-to-typescript';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));

const SCHEMAS = [
  {
    schemaPath: 'schemas/ingredient.schema.json',
    tsOut: 'packages/core/src/generated/ingredient.ts',
    tsName: 'Ingredient',
    pyOut: 'services/solver/generated/ingredient.py',
  },
];

const TS_HEADER =
  '// AUTO-GENERATED by scripts/generate-schemas.mjs from schemas/*.schema.json.\n// Do not edit by hand — see docs/data-model.md.\n\n';
const PY_HEADER =
  '# AUTO-GENERATED by scripts/generate-schemas.mjs from schemas/*.schema.json.\n# Do not edit by hand — see docs/data-model.md.\n';

async function generateTs({ schemaPath, tsOut, tsName }) {
  const schema = JSON.parse(readFileSync(resolve(rootDir, schemaPath), 'utf-8'));
  const ts = await compile(schema, tsName, {
    bannerComment: '',
    additionalProperties: false,
  });
  const outPath = resolve(rootDir, tsOut);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, TS_HEADER + ts);
  console.log(`wrote ${tsOut}`);
}

function generatePy({ schemaPath, pyOut }) {
  const outPath = resolve(rootDir, pyOut);
  mkdirSync(dirname(outPath), { recursive: true });
  execFileSync(
    'uv',
    [
      'run',
      'datamodel-codegen',
      '--input',
      resolve(rootDir, schemaPath),
      '--input-file-type',
      'jsonschema',
      '--output',
      outPath,
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--target-python-version',
      '3.12',
      '--use-standard-collections',
      '--disable-timestamp',
      '--use-schema-description',
    ],
    { cwd: resolve(rootDir, 'services/solver'), stdio: 'inherit' },
  );
  const body = readFileSync(outPath, 'utf-8');
  writeFileSync(outPath, PY_HEADER + body);
  console.log(`wrote ${pyOut}`);
}

for (const entry of SCHEMAS) {
  await generateTs(entry);
  generatePy(entry);
}

console.log('Schema codegen complete.');
